version: "3.3"

services:
  products-db:
    build: products-db
    ports:
      - "27017:27017"

  products-service:
    build: products-service
    ports:
      - "3001:3001"
    depends_on:
      - products-db

  users-db:
    build: users-db
    container_name: users-db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "users-db", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 15

  users-service:
    build: users-service
    ports:
      - "3000:3000"
    depends_on:
      users-db:
        condition: service_healthy
